[package]
name = "lend_iterator"
version = "0.1.0"
edition = "2021"
author = "Gorzorg"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
